EMAIL_MAX_LENGTH: int = 128
USERNAME_MAX_LENGTH: int = 32
USERNAME_MIN_LENGTH: int = 4
FIRST_NAME_MAX_LENGTH: int = 32
LAST_NAME_MAX_LENGTH: int = 32
STATUS_MAX_LENGTH: int = 32

USER_PHOTO_ALLOWED_EXTENSIONS: list[str] = ["jpg", "jpeg", "png"]
USER_PHOTO_SIZE: tuple[int, int] = (1080, 1080)
USER_PHOTO_QUALITY_PERCENT: int = 99
