version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./backend:/app/backend/
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: postgres:15.3-alpine
    container_name: pgdb
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - backend/.env.db
    networks:
      - backend_network

  nginx:
    image: nginx:1.27.2
    container_name: gateway
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend_network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  backend_network:
    driver: bridge
