info:
  description: ''
  title: Portfolio API
  version: ''
openapi: 3.0.0
paths:
  /api/v1/account/activation/{uid}/{token}/:
    post:
      operationId: account_activation
      parameters:
      - in: path
        name: uid
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: path
        name: token
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - account
  /api/v1/account/resend-activation/:
    post:
      operationId: account_resend_activation
      tags:
      - account
  /api/v1/account/reset-password-confirm/{uid}/{token}/:
    post:
      operationId: account_reset_password_confirm
      parameters:
      - in: path
        name: uid
        required: true
        schema:
          description: ''
          title: ''
          type: string
      - in: path
        name: token
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - account
  /api/v1/account/reset-password/:
    post:
      operationId: account_reset_password
      tags:
      - account
  /api/v1/login/:
    post:
      operationId: login_create
      tags:
      - login
  /api/v1/logout/:
    post:
      operationId: logout_create
      tags:
      - logout
  /api/v1/register/:
    post:
      operationId: register_create
      tags:
      - register
  /api/v1/users/:
    get:
      operationId: users_list
      parameters:
      - in: query
        name: is_active
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: is_vip
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: is_blocked
        schema:
          description: ''
          title: ''
          type: string
      - in: query
        name: search
        schema:
          description: A search term.
          title: Search
          type: string
      tags:
      - users
    post:
      operationId: users_create
      tags:
      - users
  /api/v1/users/activation/:
    post:
      operationId: users_activation
      tags:
      - users
  /api/v1/users/resend_activation/:
    post:
      operationId: users_resend_activation
      tags:
      - users
  /api/v1/users/reset_password/:
    post:
      operationId: users_reset_password
      tags:
      - users
  /api/v1/users/reset_password_confirm/:
    post:
      operationId: users_reset_password_confirm
      tags:
      - users
  /api/v1/users/reset_username/:
    post:
      operationId: users_reset_username
      tags:
      - users
  /api/v1/users/reset_username_confirm/:
    post:
      operationId: users_reset_username_confirm
      tags:
      - users
servers:
- url: http://localhost/api/schema/?format=openapi
